export const rows = [
    {
        id: 1,
        name: 'Othmane',
        email: 'othmane@example.com',
        age: 25,
        phone: '+213558560238',
        address: 'Algeria',
        city: 'Setif',
        zipCode: '19000',
        registrarId: 216,
    },
    {
        id: 2,
        name: 'Amine',
        email: 'amine@example.com',
        age: 28,
        phone: '+213554332198',
        address: 'Algeria',
        city: 'Algiers',
        zipCode: '16000',
        registrarId: 217,
    },
    {
        id: 3,
        name: 'Sara',
        email: 'sara@example.com',
        age: 22,
        phone: '+213662214589',
        address: 'Algeria',
        city: 'Oran',
        zipCode: '31000',
        registrarId: 218,
    },
    {
        id: 4,
        name: 'Mohamed',
        email: 'mohamed@example.com',
        age: 30,
        phone: '+213557892134',
        address: 'Algeria',
        city: 'Constantine',
        zipCode: '25000',
        registrarId: 219,
    },
    {
        id: 5,
        name: 'Nour',
        email: 'nour@example.com',
        age: 27,
        phone: '+213551236789',
        address: 'Algeria',
        city: 'Annaba',
        zipCode: '23000',
        registrarId: 220,
    },
    {
        id: 6,
        name: 'Khaled',
        email: 'khaled@example.com',
        age: 35,
        phone: '+213553456890',
        address: 'Algeria',
        city: 'Tlemcen',
        zipCode: '13000',
        registrarId: 221,
    },
    {
        id: 7,
        name: 'Yasmine',
        email: 'yasmine@example.com',
        age: 24,
        phone: '+213664789123',
        address: 'Algeria',
        city: 'Batna',
        zipCode: '05000',
        registrarId: 222,
    },
    {
        id: 8,
        name: 'Samir',
        email: 'samir@example.com',
        age: 29,
        phone: '+213559876432',
        address: 'Algeria',
        city: 'Blida',
        zipCode: '09000',
        registrarId: 223,
    },
    {
        id: 9,
        name: 'Lina',
        email: 'lina@example.com',
        age: 31,
        phone: '+213554328976',
        address: 'Algeria',
        city: 'Bejaia',
        zipCode: '06000',
        registrarId: 224,
    },
    {
        id: 10,
        name: 'Ahmed',
        email: 'ahmed@example.com',
        age: 26,
        phone: '+213551876543',
        address: 'Algeria',
        city: 'Ghardaia',
        zipCode: '47000',
        registrarId: 225,
    },
];


export const columns = [
    { field: 'id', headerName: 'ID', width: 70 },
    { field: 'name', headerName: 'Name', width: 150 },
    { field: 'email', headerName: 'Email', width: 200 },
    { field: 'age', headerName: 'Age', width: 100 },
    { field: 'phone', headerName: 'Phone', width: 150 },
    { field: 'address', headerName: 'Address', width: 150 },
    { field: 'city', headerName: 'City', width: 120 },
    { field: 'zipCode', headerName: 'Zip Code', width: 120 },
    { field: 'registrarId', headerName: 'Registrar ID', width: 120 },
];
